# default
spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  batch:
    job:
      names: ${job.name:NONE}  # Job ??? ????? ??? ???
      enabled: false # 설정에 파라미터를 무시(스케줄용)
    jdbc:
      initialize-schema: ALWAYS # ?? ???
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true